---
- hosts: all
  become: yes
  gather_facts: False
  tasks:
    - name: Install base packages
      apt:
        name: ['git', 'python-pip', 'python3-pip', 'python-setuptools']
        state: present
      tags:
        - packages
        
    - name: Redirigir puertos
      become: true
      lineinfile:
        path=/etc/rc.local
        insertbefore='exit 0'
        line="sudo iptables -t nat -I PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 5000"
