title: Prácticas de la asignatura Cloud Computing
description: Andrea Morales Garzón - Máster Ingeniería Informática de la Universidad de Granada
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
